#!/bin/python3

from subprocess import Popen
from datetime import datetime

t = datetime.now().strftime('%Y_%b_%d@%H_%M_%S')

sbatch_filename = f'auto_{t}.sbatch'

with open('train.sbatch', 'r') as fin:
    with open(sbatch_filename, 'w') as fout:
        for line in fin:
            fout.write(line.replace(
                'slurm_train', f'slurm_{t}', 
            ))

with Popen(['sbatch', sbatch_filename]) as p:
    p.wait()
